@startuml
'https://plantuml.com/use-case-diagram

rectangle "<<Aggregate>> Course" #lightskyblue{

    entity Course<<Root>><<Entity>>
    object Id<<Value Object>><<Identify>>
    object CourseState<<Value Object>>
    object CourseEnrollmentState <<Value Object>>
    object Edition <<Value Object>>
    object CourseDescription <<Value Object>>
    object CourseTitle <<Value Object>>

    Course"1" --> "1"CourseTitle: has a
    Course"1" --> "1"Id : has a
    Course"1" --> "1"CourseDescription : has a
    Course"1"-->"1"CourseState : has a
    Course"1"-->"1"CourseEnrollmentState: has an
    Course"1" -->"1"Edition : has a
}

rectangle "<<Aggregate>> Personal Information" #bbaabb{

    entity User<<Root>><<Entity>><<Strategy>>
    object BirthDate<<Value Object>>
    object TaxNumber<<Value Object>><<Id>>
    object FullName<<Value Object>>
    object ShortName<<Value Object>>

    User"1" -up-> "1"BirthDate : has a
    User"1" -left-> "1"TaxNumber : has a
    User"1" --> "1" FullName : has a
    User "1" -up->"1"ShortName : has a
}

rectangle "<<Aggregate>> Student" #hotpink{

    entity Student<<Entity>><<Root>>
    object MechanographicNumber<<Value Object>>

    Student -up-> User: is a
    Student "1" -->"1"MechanographicNumber: has a
}

rectangle "<<Aggregate>> Enrollment" #slategrey {

    entity Enrollment
    object EnrollmentState<<Value Object>>

     Enrollment"1"-->"1"EnrollmentState : has an
     Enrollment "1"-->"1" Course : is related to a >
}

Student--> Enrollment: makes a


@enduml