@startuml

Actor Student

activate Student
Student -> System: I want to take an Exam
activate System
System --> Student: Shows available exams
deactivate System
Student -> System: Selects the exam
activate System
System --> Student: Creates the Exam
deactivate System
Student -> System: Does the Exam
activate System
System --> Student: Prints Evaluation Details
deactivate System
deactivate Student

@enduml