@startuml
'http://plantuml.com/skinparam.html


hide field
hide methods

title Domain Driven Design

skinparam linetype ortho

rectangle "<<Aggregate>> ChargeTeacher" #mediumslateblue{
    entity "ChargeTeacher"<<Root>><<Entity>>
}

rectangle "<<Aggregate>> Teacher" #blueviolet{

    entity Teacher<<Entity>><<Root>>
    object Acronym<<Value Object>>

    Teacher -up|> User: is a
    Teacher"1" --> "1"Acronym : has a
    ChargeTeacher "1"--|>"1" Teacher : is a
}


rectangle "<<Aggregate>> Course" #lightskyblue{

    entity Course<<Root>><<Entity>>
    object Id<<Value Object>><<Identify>>
    object CourseState<<Value Object>>
    object CourseEnrollmentState <<Value Object>>
    object Edition <<Value Object>>
    object CourseDescription <<Value Object>>
    object CourseTitle <<Value Object>>

    Course"1" --> "1"CourseTitle: has a
    Course"1" --> "1"Id : has a
    Course"1" --> "1"CourseDescription : has a
    Course"1"-->"1"CourseState : has a
    Course"1"-->"1"CourseEnrollmentState: has an
    Course"1" -->"1"Edition : has a
    Course"1" -->"1"ChargeTeacher: needs a
}

rectangle "<<Aggregate>> Student" #hotpink{

    entity Student<<Entity>><<Root>>
    object MechanographicNumber<<Value Object>>

    Student -up|> User
    Student "1" -->"1"MechanographicNumber: has a
    Student "1"-->"1"FinishedExam: answers
}

rectangle "<<Aggregate>> Enrollment" #slategrey {

    entity Enrollment
    object EnrollmentState<<Value Object>>

     Enrollment"1"-->"1"EnrollmentState : has an
}

rectangle "<<Aggregate>> EnrollmentApprovation" #slategrey {

    entity EnrollmentApprovation
    object Justification<<Value Object>>

     EnrollmentApprovation"1"-->"1"Justification: has an
     EnrollmentApprovation"1"-->"1..*"Enrollment: approves
}


Student "1"-->"1...*" Enrollment : makes an >
Enrollment "1"-->"1" Course : is related to a >




@enduml

